apply plugin: 'com.android.library'
apply plugin: 'com.joom.paranoid'

android {
  namespace 'com.joom.paranoid.processor.subproject.android'
  compileSdk androidCompileSdkVersion

  buildFeatures {
    buildConfig = true
  }

  defaultConfig {
    namespace "com.joom.paranoid.processor.subproject.android"
    minSdkVersion androidMinSdkVersion
    targetSdkVersion androidTargetSdkVersion
    versionCode 1
    versionName version
  }

  compileOptions {
    sourceCompatibility javaVersion
    targetCompatibility javaVersion
  }
}
