buildscript {
  apply from: '../versions.gradle'

  repositories {
    mavenLocal()
    google()
    mavenCentral()
    gradlePluginPortal()
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    classpath "com.android.tools.build:gradle:$androidToolsVersion"
    classpath "com.vanniktech:gradle-maven-publish-plugin:$mavenPublishVersion"
    classpath "com.gradleup.shadow:shadow-gradle-plugin:$shadowVersion"
  }
}

allprojects {
  version = PARANOID_VERSION
  group = PARANOID_GROUP

  repositories {
    mavenLocal()
    google()
    mavenCentral()
  }
}

apply plugin: 'kotlin'

dependencies {
  testImplementation gradleTestKit()
  testImplementation "junit:junit:$junitVersion"
}

tasks.register("functionalTest", Test.class) {
  description = "Runs the functional tests."
  group = "verification"

  testClassesDirs = sourceSets.test.output.classesDirs
  classpath = sourceSets.test.runtimeClasspath
}

afterEvaluate {
  tasks.named("functionalTest") {
    subprojects.each {
      dependsOn(it.tasks.named("publishToMavenLocal"))
    }
  }
}
