buildscript {
  dependencies {
    classpath "com.joom.paranoid:paranoid-gradle-plugin:$version"
  }
}

apply plugin: 'com.android.application'
apply plugin: 'com.joom.paranoid'

android {
  namespace 'com.joom.paranoid.sample'
  compileSdk androidCompileSdkVersion

  defaultConfig {
    applicationId 'com.joom.paranoid.sample'
    minSdkVersion androidMinSdkVersion
    targetSdkVersion androidTargetSdkVersion
    versionCode 1
    versionName version

    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }

  signingConfigs {
    release {
      storeFile = file('release.keystore')
      storePassword = 'paranoid'
      keyAlias = 'paranoid'
      keyPassword = 'paranoid'
    }
  }

  buildTypes {
    debug {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }

    release {
      minifyEnabled true
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
      signingConfig signingConfigs.release
    }
  }

  compileOptions {
    sourceCompatibility javaVersion
    targetCompatibility javaVersion
  }
}

kotlin {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
  }
}

dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib$kotlinRuntimeVariant:$kotlinVersion"
  implementation "androidx.appcompat:appcompat:$androidxAppcompatVersion"

  testImplementation "junit:junit:$junitVersion"

  androidTestImplementation "androidx.test:rules:$androidxRulesVersion"
  androidTestImplementation "androidx.test:runner:$androidxRunnerVersion"
  androidTestImplementation "androidx.test.ext:junit:$androidxTestExtJunitVersion"
  androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoVersion"
}
