apply plugin: 'com.android.application'
apply plugin: 'com.joom.paranoid'

android {
  namespace 'com.joom.paranoid.processor.subproject'
  compileSdk androidCompileSdkVersion

  defaultConfig {
    applicationId 'com.joom.paranoid.processor.subproject'
    minSdkVersion androidMinSdkVersion
    targetSdkVersion androidTargetSdkVersion
    versionCode 1
    versionName version

    testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
  }

  buildTypes {
    release {
      minifyEnabled false
    }
  }

  compileOptions {
    sourceCompatibility javaVersion
    targetCompatibility javaVersion
  }
}

kotlin {
  compilerOptions {
    jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
  }
}

dependencies {
  implementation project(':processor-tests:subproject-android')
  implementation project(':processor-tests:subproject-java')

  implementation "org.jetbrains.kotlin:kotlin-stdlib$kotlinRuntimeVariant:$kotlinVersion"

  androidTestImplementation "androidx.annotation:annotation:$androidxAnnotationVersion"
  androidTestImplementation "androidx.test:rules:$androidxRulesVersion"
  androidTestImplementation "androidx.test:runner:$androidxRunnerVersion"
  androidTestImplementation "androidx.test.ext:junit:$androidxTestExtJunitVersion"
  androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoVersion"
}

paranoid {
  obfuscationSeed version.hashCode()
}
